name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    # webフォルダに変更があった時だけ動かす
    paths:
      - 'typecast-web/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 依存関係のインストールとビルド
      - name: Install and Build
        working-directory: ./typecast-web # webフォルダの中で実行
        env:
          VITE_API_URL: '${{ secrets.VITE_API_URL }}'
          VITE_FIREBASE_API_KEY: '${{ secrets.VITE_FIREBASE_API_KEY }}'
          VITE_FIREBASE_AUTH_DOMAIN: '${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}'
          VITE_FIREBASE_PROJECT_ID: '${{ secrets.VITE_FIREBASE_PROJECT_ID }}'
          VITE_FIREBASE_STORAGE_BUCKET: '${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}'
          VITE_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}'
          VITE_FIREBASE_APP_ID: '${{ secrets.VITE_FIREBASE_APP_ID }}'
        run: |
          npm ci
          npm run build

      # 2. Firebase Hostingへのデプロイ
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}' # 既存の鍵を再利用
          channelId: live # 本番環境(live)にデプロイ
          projectId: '${{ secrets.GCP_PROJECT_ID }}'
          entryPoint: ./typecast-web # firebase.jsonがある場所を指定